run_name: vpwiki
seed: 43
pretrained_model: './clip-vit-base-patch32'
lr: 1e-5


data:
  ###########检查图片文件夹，检查各个数据集文件是否正确


  num_entity: 132460
  kb_img_folder: /kb_image/
  mention_img_folder: /test_img/
  qid2id: /qid2id.json
  entity: /kb_entity.json
  train_file: /train.json
  dev_file: /dev.json
  test_file: /test.json


  batch_size: 128
  num_workers: 8
  text_max_length: 40

  eval_chunk_size: 6000
  eval_batch_size: 20
  embed_update_batch_size: 512


model:
  input_hidden_dim: 512
  input_image_hidden_dim: 768
  hidden_dim: 96
  dv: 96
  dt: 512
  TGLU_hidden_dim: 96
  IDLU_hidden_dim: 96
  CMFU_hidden_dim: 96


trainer:
  accelerator: 'gpu'
  devices: 1
  max_epochs: 20
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 2
  log_every_n_steps: 30
